# Generated by Django 3.0.6 on 2020-05-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customar',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customar',
            name='phone',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
