# Generated by Django 3.0.6 on 2020-05-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200505_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customar',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
